# ── Vocabulary: Lección 5 — Un Festival de Arte ───────────────────────────────

VOCABULARY = {
    "el baile": ["dance"], "la danza": ["dance"], "el boleto": ["ticket"],
    "la canción": ["song"], "el concierto": ["concert"], "la comedia": ["comedy"],
    "el cuento": ["story", "short story"], "la cultura": ["culture"],
    "el drama": ["drama"], "la tragedia": ["tragedy"], "la escultura": ["sculpture"],
    "el espectáculo": ["show", "spectacle", "performance"], "la estatua": ["statue"],
    "el festival": ["festival"], "la historia": ["history", "story"],
    "la música": ["music"], "la obra": ["work", "play"], "el crítico": ["critic"],
    "la crítica": ["criticism", "critique", "review"], "la obra maestra": ["masterpiece"],
    "la ópera": ["opera"], "la zarzuela": ["musical", "spanish musical"],
    "la orquesta": ["orchestra"], "el personaje": ["character"],
    "el protagonista": ["protagonist", "main character"], "la pintura": ["painting"],
    "la poesía": ["poetry"], "el público": ["audience", "public"],
    "el teatro": ["theater", "theatre"], "la taquilla": ["ticket booth", "box office"],
    "el papel": ["role", "paper"], "los instrumentos": ["instruments"],
    "artístico": ["artistic"], "clásico": ["classic", "classical"],
    "dramático": ["dramatic"], "extranjero": ["foreign"],
    "folclórico": ["folkloric", "folk"], "moderno": ["modern"],
    "romántico": ["romantic"], "talentoso": ["talented"],
    "la cerámica": ["ceramics", "pottery"], "el tejido": ["knitting", "weaving", "fabric"],
    "la fotografía": ["photography"], "el bailarín": ["dancer", "male dancer"],
    "la bailarina": ["dancer", "female dancer", "ballerina"],
    "el/la cantante": ["singer"], "el/la compositor/a": ["composer"],
    "el/la director/a": ["director"], "el/la dramaturgo/a": ["playwright"],
    "el/la escritor/a": ["writer", "author"],
    "la estrella de cine": ["movie star", "film star"], "el músico": ["musician"],
    "el poeta": ["poet"], "la poetisa": ["poetess", "poet"],
    "el/la artesano/a": ["artisan", "craftsperson"],
    "el actor / la actriz": ["actor", "actress"], "el canal": ["channel"],
    "el concurso": ["competition", "contest", "game show"],
    "los dibujos animados": ["cartoons", "animations"],
    "el documental": ["documentary"], "el premio": ["award", "prize"],
    "la realidad": ["reality"],
    "el programa de entrevistas": ["talk show", "interview show"],
    "la telenovela": ["soap opera"], "de acción": ["action"],
    "de aventuras": ["adventure"], "de terror": ["horror", "terror"],
    "de horror": ["horror"], "de ciencia ficción": ["science fiction", "sci-fi"],
    "de vaqueros": ["western", "cowboy"], "romántica": ["romantic"],
    "histórica": ["historical", "historic"],
    "basada en un hecho real": ["based on a true story"],
    "dibujar": ["to draw"], "bailar": ["to dance"], "cantar": ["to sing"],
    "escribir": ["to write"], "declamar": ["to recite", "to declaim"],
    "pintar": ["to paint"], "esculpir": ["to sculpt"],
    "aburrirse": ["to get bored", "to be bored"],
    "divertirse": ["to have fun", "to enjoy oneself"],
    "aplaudir": ["to applaud", "to clap"], "apreciar": ["to appreciate"],
    "criticar": ["to criticize"], "dirigir": ["to direct"],
    "hacer el papel de": ["to play the role of"],
    "interpretar": ["to perform", "to interpret"], "presentar": ["to present"],
    "publicar": ["to publish"], "tocar": ["to play (instrument)", "to touch"],
    "dramatizar": ["to dramatize"], "actuar": ["to act"],
    "componer": ["to compose"], "tejer": ["to knit", "to weave"],
}

# ── Vocabulary: Un Sinnúmero de Números ──────────────────────────────────────

VOCABULARY_NUMBERS = {
    "cero":              ["zero", "0"],
    "uno / un":          ["one", "1"],
    "dos":               ["two", "2"],
    "tres":              ["three", "3"],
    "cuatro":            ["four", "4"],
    "cinco":             ["five", "5"],
    "seis":              ["six", "6"],
    "siete":             ["seven", "7"],
    "ocho":              ["eight", "8"],
    "nueve":             ["nine", "9"],
    "diez":              ["ten", "10"],
    "once":              ["eleven", "11"],
    "doce":              ["twelve", "12"],
    "trece":             ["thirteen", "13"],
    "catorce":           ["fourteen", "14"],
    "quince":            ["fifteen", "15"],
    "dieciséis":         ["sixteen", "16"],
    "diecisiete":        ["seventeen", "17"],
    "dieciocho":         ["eighteen", "18"],
    "diecinueve":        ["nineteen", "19"],
    "veinte":            ["twenty", "20"],
    "veintiuno":         ["twenty-one", "21"],
    "veintidós":         ["twenty-two", "22"],
    "veintitrés":        ["twenty-three", "23"],
    "treinta":           ["thirty", "30"],
    "cuarenta":          ["forty", "40"],
    "cincuenta":         ["fifty", "50"],
    "sesenta":           ["sixty", "60"],
    "setenta":           ["seventy", "70"],
    "ochenta":           ["eighty", "80"],
    "noventa":           ["ninety", "90"],
    "cien / ciento":     ["one hundred", "100", "hundred"],
    "doscientos":        ["two hundred", "200"],
    "trescientos":       ["three hundred", "300"],
    "cuatrocientos":     ["four hundred", "400"],
    "quinientos":        ["five hundred", "500"],
    "seiscientos":       ["six hundred", "600"],
    "setecientos":       ["seven hundred", "700"],
    "ochocientos":       ["eight hundred", "800"],
    "novecientos":       ["nine hundred", "900"],
    "mil":               ["one thousand", "1000", "thousand"],
    "dos mil":           ["two thousand", "2000"],
    "tres mil":          ["three thousand", "3000"],
    "diez mil":          ["ten thousand", "10000"],
    "cien mil":          ["one hundred thousand", "100000"],
    "quinientos mil":    ["five hundred thousand", "500000"],
    "un millón":         ["one million", "1000000"],
    "primero / primer":          ["first", "1st"],
    "segundo":                   ["second", "2nd"],
    "tercero / tercer":          ["third", "3rd"],
    "cuarto":                    ["fourth", "4th"],
    "quinto":                    ["fifth", "5th"],
    "sexto":                     ["sixth", "6th"],
    "séptimo":                   ["seventh", "7th"],
    "octavo":                    ["eighth", "8th"],
    "noveno":                    ["ninth", "9th"],
    "décimo":                    ["tenth", "10th"],
    "undécimo":                  ["eleventh", "11th"],
    "duodécimo":                 ["twelfth", "12th"],
    "decimotercero":             ["thirteenth", "13th"],
    "decimocuarto":              ["fourteenth", "14th"],
    "decimoquinto":              ["fifteenth", "15th"],
    "decimosexto":               ["sixteenth", "16th"],
    "decimoséptimo":             ["seventeenth", "17th"],
    "decimoctavo":               ["eighteenth", "18th"],
    "decimonoveno":              ["nineteenth", "19th"],
    "vigésimo":                  ["twentieth", "20th"],
    "vigésimo primero":          ["twenty-first", "21st"],
    "vigésimo segundo":          ["twenty-second", "22nd"],
    "vigésimo tercero":          ["twenty-third", "23rd"],
    "trigésimo":                 ["thirtieth", "30th"],
    "trigésimo primero":         ["thirty-first", "31st"],
    "trigésimo segundo":         ["thirty-second", "32nd"],
    "trigésimo tercero":         ["thirty-third", "33rd"],
    "cuadragésimo":              ["fortieth", "40th"],
    "quincuagésimo":             ["fiftieth", "50th"],
    "sexagésimo":                ["sixtieth", "60th"],
    "septuagésimo":              ["seventieth", "70th"],
    "octogésimo":                ["eightieth", "80th"],
    "nonagésimo":                ["ninetieth", "90th"],
    "centésimo":                 ["hundredth", "100th"],
    "centésimo primero":         ["one hundred first", "101st"],
    "centésimo segundo":         ["one hundred second", "102nd"],
    "ducentésimo":               ["two hundredth", "200th"],
    "tricentésimo":              ["three hundredth", "300th"],
    "cuadringentésimo":          ["four hundredth", "400th"],
    "quingentésimo":             ["five hundredth", "500th"],
    "sexcentésimo":              ["six hundredth", "600th"],
    "septingentésimo":           ["seven hundredth", "700th"],
    "octingentésimo":            ["eight hundredth", "800th"],
    "noningentésimo":            ["nine hundredth", "900th"],
    "milésimo":                  ["thousandth", "1000th"],
    "milésimo primero":          ["one thousand first", "1001st"],
    "dosmilésimo":               ["two thousandth", "2000th"],
    "tresmilésimo":              ["three thousandth", "3000th"],
    "diezmilésimo":              ["ten thousandth", "10000th"],
    "cienmilésimo":              ["hundred thousandth", "100000th"],
    "quinientosmilésimo":        ["five hundred thousandth", "500000th"],
    "millonésimo":               ["millionth", "1000000th"],
}

# ── Vocabulary: Lección 4 — El Mundo del Trabajo ─────────────────────────────

VOCABULARY_L4 = {
    "el/la abogado/a": ["lawyer"], "el actor": ["actor"],
    "la actriz": ["actress"], "el/la arqueólogo/a": ["archaeologist"],
    "el/la arquitecto/a": ["architect"], "el/la bombero/a": ["firefighter"],
    "el/la carpintero/a": ["carpenter"], "el/la científico/a": ["scientist"],
    "el/la cocinero/a": ["cook", "chef"], "el/la consejero/a": ["counselor", "advisor"],
    "el/la contador/a": ["accountant"],
    "el/la corredor/a de bolsa": ["stockbroker"],
    "el/la diseñador/a": ["designer"], "el/la electricista": ["electrician"],
    "el hombre de negocios": ["businessman"],
    "la mujer de negocios": ["businesswoman"],
    "el/la maestro/a": ["teacher"], "el/la profesor/a": ["professor", "teacher"],
    "el/la peluquero/a": ["hairdresser", "barber"],
    "el/la pintor/a": ["painter"], "el/la político/a": ["politician"],
    "el/la psicólogo/a": ["psychologist"], "el/la reportero/a": ["reporter"],
    "el/la periodista": ["journalist"], "el/la secretario/a": ["secretary"],
    "el/la técnico/a": ["technician"], "el/la doctor/a": ["doctor"],
    "el/la enfermero/a": ["nurse"], "el/la dentista": ["dentist"],
    "derecho": ["law"], "actuación": ["acting"],
    "arqueología": ["archaeology"], "culinaria": ["culinary arts"],
    "consejería": ["counseling"], "economía": ["economics"],
    "diseño": ["design"], "periodismo": ["journalism"],
    "medicina": ["medicine"], "odontología": ["dentistry"],
    "el ascenso": ["promotion", "raise"], "la promoción": ["promotion"],
    "el aumento": ["raise", "increase"],
    "el sueldo": ["salary", "wage"], "el salario": ["salary"],
    "la carrera": ["career"], "la compañía": ["company"],
    "la empresa": ["company", "business"], "la firma": ["firm", "signature"],
    "el puesto": ["position", "job"],
    "el/la gerente": ["manager"], "el/la jefe/a": ["boss"],
    "los negocios": ["business"], "la ocupación": ["occupation"],
    "el oficio": ["trade", "craft"], "el título": ["degree", "title"],
    "la profesión": ["profession"], "la reunión": ["meeting"],
    "el teletrabajo": ["remote work", "telework"],
    "el trabajo": ["work", "job"], "la oficina": ["office"],
    "comercial": ["commercial"], "dentro de": ["within"],
    "próximo": ["next"], "vacaciones": ["vacation"],
    "sobresueldo": ["bonus"],
    "el anuncio": ["advertisement", "announcement"],
    "el/la aspirante": ["applicant", "candidate"],
    "los beneficios": ["benefits"],
    "el currículo": ["résumé", "CV"], "la hoja de vida": ["résumé", "CV"],
    "el entrevistado": ["interviewee"], "el entrevistador": ["interviewer"],
    "la solicitud de trabajo": ["job application"],
    "ascender": ["to promote", "to rise"], "graduarse": ["to graduate"],
    "contratar": ["to hire"], "entrevistar": ["to interview"],
    "ganar": ["to earn", "to win"], "obtener": ["to obtain", "to get"],
    "solicitar": ["to apply for", "to request"], "defender": ["to defend"],
    "estudiar": ["to study"], "aplicar": ["to apply"],
    "buscar": ["to search", "to look for"],
    "aumentar": ["to increase", "to raise"], "emplear": ["to employ"],
    "negociar": ["to negotiate"],
    "reunirse": ["to meet", "to get together"], "trabajar": ["to work"],
    "dejar": ["to leave", "to quit"], "despedir": ["to fire", "to dismiss"],
    "invertir": ["to invest"], "aceptar": ["to accept"],
    "renunciar": ["to resign", "to give up"],
    "tener éxito": ["to succeed", "to be successful"],
    "comerciar": ["to trade"],
}

# ── Vocabulary: Lección 6 — La Actualidad ────────────────────────────────────

VOCABULARY_L6 = {
    "el acontecimiento": ["event"],
    "la actualidad": ["current events", "present time"],
    "las noticias": ["news"],
    "las noticias de última hora": ["breaking news"],
    "el artículo": ["article"],
    "el diario": ["newspaper", "diary"],
    "el periódico": ["newspaper"],
    "el informe": ["report"],
    "el locutor": ["announcer", "broadcaster"],
    "la locutora": ["announcer", "broadcaster"],
    "el noticiero": ["newscast", "news program"],
    "la prensa": ["press"],
    "el reportaje": ["report", "news story"],
    "el radio": ["radio"],
    "el choque": ["crash", "collision"],
    "el crimen": ["crime"],
    "el desastre natural": ["natural disaster"],
    "el terremoto": ["earthquake"],
    "el maremoto": ["tsunami", "tidal wave"],
    "el sunami": ["tsunami"],
    "la tormenta": ["storm"],
    "el tornado": ["tornado"],
    "el huracán": ["hurricane"],
    "el incendio": ["fire"],
    "el empleo": ["employment"],
    "el desempleo": ["unemployment"],
    "la desigualdad": ["inequality"],
    "la discriminación": ["discrimination"],
    "el ejército": ["army"],
    "la huelga": ["strike"],
    "el paro": ["strike", "unemployment"],
    "el secuestro": ["kidnapping"],
    "la inundación": ["flood"],
    "la libertad": ["freedom", "liberty"],
    "la guerra": ["war"],
    "la paz": ["peace"],
    "el racismo": ["racism"],
    "el sexismo": ["sexism"],
    "el SIDA": ["AIDS"],
    "el soldado": ["soldier"],
    "la violencia": ["violence"],
    "la policía": ["police"],
    "el peligro": ["danger"],
    "el candidato": ["candidate"],
    "la candidata": ["candidate"],
    "el ciudadano": ["citizen"],
    "el deber": ["duty"],
    "los derechos": ["rights"],
    "la dictadura": ["dictatorship"],
    "la opresión": ["oppression"],
    "el atraco": ["holdup", "robbery", "mugging"],
    "el robo": ["heist", "robbery", "theft"],
    "el engaño": ["deception", "deceit"],
    "la decepción": ["disappointment"],
    "el discurso": ["speech"],
    "las elecciones": ["elections"],
    "la encuesta": ["survey", "poll"],
    "la entrevista": ["interview"],
    "los impuestos": ["taxes"],
    "el representante": ["representative"],
    "internacional": ["international"],
    "el voto": ["vote"],
    "anunciar": ["to announce"],
    "comunicarse": ["to communicate"],
    "durar": ["to last"],
    "votar": ["to vote"],
    "elegir": ["to choose", "to elect"],
    "informar": ["to inform"],
    "ocurrir": ["to occur", "to happen"],
    "transmitir": ["to transmit", "to broadcast"],
    "emitir": ["to emit", "to broadcast"],
    "declarar": ["to declare"],
    "luchar": ["to fight", "to struggle"],
    "seguir": ["to follow", "to continue"],
    "cumplir": ["to fulfill", "to comply"],
    "obedecer": ["to obey"],
    "despedirse": ["to say goodbye"],
    "¡Qué gusto!": ["What a pleasure!"],
    "¡Mucho gusto!": ["Nice to meet you!"],
    "¡No tenía ni idea!": ["I had no idea!"],
    "¡Felicidades!": ["Congratulations!"],
    "¡Enhorabuena!": ["Congratulations!"],
    "¡La he pasado de película!": ["I had an amazing time!"],
    "¡Me suena excelente!": ["Sounds great to me!"],
    "Como si …": ["as if"],
}

# ── Vocabulary: El Subjuntivo con Expresiones Impersonales ────────────────────
# (yellow sheet — all expressions trigger subjunctive except the ★★☺ group)

VOCABULARY_SUBJ_IMPERSONAL = {
    "es absurdo":          ["it's absurd"],
    "es agradable":        ["it's agreeable", "it's pleasant"],
    "es bueno":            ["it is good"],
    "es conveniente":      ["it is convenient"],
    "es difícil":          ["it is difficult"],
    "es dudoso":           ["it's doubtful"],
    "es escandaloso":      ["it's scandalous"],
    "es extraño":          ["it's strange"],
    "es raro":             ["it's strange", "it's weird"],
    "es fácil":            ["it is easy"],
    "es importante":       ["it is important"],
    "es imposible":        ["it is impossible"],
    "es improbable":       ["it is improbable"],
    "es inconveniente":    ["it is inconvenient", "it is unsuitable"],
    "es indispensable":    ["it's indispensable"],
    "es inútil":           ["it is useless"],
    "es increíble":        ["it is incredible", "it is unbelievable"],
    "es justo":            ["it is just", "it is proper"],
    "es una lástima":      ["it is a shame"],
    "es malo":             ["it is bad"],
    "es mejor":            ["it is best", "it is better"],
    "es natural":          ["it is natural"],
    "es necesario":        ["it is necessary"],
    "es normal":           ["it's normal"],
    "es peor":             ["it is worse"],
    "es posible":          ["it is possible"],
    "es probable":         ["it is probable", "it is likely"],
    "es ridículo":         ["it's ridiculous"],
    "es sorprendente":     ["it is surprising"],
    "es triste":           ["it's sad"],
    "es terrible":         ["it's terrible"],
    "es fantástico":       ["it's fantastic"],
    "es urgente":          ["it's urgent"],
    "es útil":             ["it is useful"],
    "más vale":            ["it is better"],
    "parece increíble":    ["it seems incredible"],
    "parece mentira":      ["it seems untrue"],
    "puede ser":           ["it may be"],
    "vale la pena":        ["it is worthwhile"],
    # ★★☺ group — these take INDICATIVE
    "es cierto":           ["it is certain"],
    "es claro":            ["it is clear"],
    "es evidente":         ["it is evident"],
    "es obvio":            ["it is obvious"],
    "es seguro":           ["it is sure"],
    "es verdad":           ["it is true"],
    "no hay duda":         ["there is no doubt"],
}

# ── Vocabulary: El Subjuntivo con Expresiones de Duda e Incertidumbre ─────────
# (green sheet)

VOCABULARY_SUBJ_DOUBT = {
    # → subjuntivo group
    "dudar":               ["to doubt"],
    "negar":               ["to deny"],
    "no creer":            ["to not believe"],
    "no pensar":           ["to not think"],
    "no estar seguro/a de": ["to not be sure"],
    "no es seguro":        ["it is not sure"],
    "no es cierto":        ["it is not certain"],
    "no es verdad":        ["it is not true"],
    "quizás":              ["perhaps", "maybe"],
    "tal vez":             ["perhaps", "maybe"],
    # → indicativo group
    "no dudar":            ["to not doubt"],
    "no negar":            ["to not deny"],
    "creer":               ["to believe"],
    "pensar":              ["to think"],
    "estar seguro/a de":   ["to be sure"],
    "es cierto":           ["it is certain"],
    "es verdad":           ["it is true"],
}

# ── Vocabulary: Expresiones de Voluntad y Deseo con el Subjuntivo ─────────────
# (violet sheet — upper vocabulary section only)

VOCABULARY_SUBJ_WILL = {
    "ojalá":               ["hopefully"],
    "esperar":             ["to hope", "to expect"],
    "querer":              ["to want"],
    "desear":              ["to desire", "to wish"],
    "preferir":            ["to prefer"],
    "recomendar":          ["to recommend"],
    "sugerir":             ["to suggest"],
    "insistir en":         ["to insist"],
    "decir":               ["to say", "to tell"],
    "necesitar":           ["to need"],
    "pedir":               ["to ask", "to request"],
    "mandar":              ["to command", "to order"],
    "exigir":              ["to demand"],
    "suplicar":            ["to plead"],
    "rogar":               ["to beg"],
    "oponerse a":          ["to oppose"],
    "aconsejar":           ["to advise"],
    "dejar":               ["to allow"],
    "permitir":            ["to permit"],
    "prohibir":            ["to prohibit"],
}

# ── Práctica lessons ──────────────────────────────────────────────────────────
#
# Each exercise has:
#   before   — text before the blank
#   after    — text after the blank (empty string if blank is at the end)
#   hint     — infinitive shown in parentheses on the worksheet
#   answer   — primary correct answer
#   alts     — list of additional accepted answers
#
# Lessons with an "intro" key show an explanation screen before the exercises.
# intro is a list of blocks: {"type": "rule"|"examples"|"note", ...}

PRACTICA_LESSONS: dict[str, dict] = {
    # ── Lesson 1: green sheet ─────────────────────────────────────────────────
    "1": {
        "title": "Duda e Incertidumbre",
        "subtitle": "Subjuntivo vs. Indicativo",
        "intro": None,
        "exercises": [
            {
                "before": "Dudamos que la universidad",
                "after":  "a Luisa el año que viene.",
                "hint":   "aceptar",
                "answer": "acepte",
                "alts":   [],
            },
            {
                "before": "No estoy seguro que yo",
                "after":  "acompañarte a la fiesta este fin de semana.",
                "hint":   "poder",
                "answer": "pueda",
                "alts":   [],
            },
            {
                "before": "Ellos no creen que el dinero",
                "after":  "el problema.",
                "hint":   "ser",
                "answer": "sea",
                "alts":   [],
            },
            {
                "before": "Estás muy enfermo. Yo pienso que tú",
                "after":  "ir al doctor mañana.",
                "hint":   "necesitar",
                "answer": "necesitas",
                "alts":   [],
            },
            {
                "before": "El señor no niega que a veces",
                "after":  "las luces prendidas.",
                "hint":   "dejar",
                "answer": "deja",
                "alts":   [],
            },
            {
                "before": "Dudo que mi hermano",
                "after":  "a casa antes de las 11:00 anoche.",
                "hint":   "volver",
                "answer": "volviera",
                "alts":   ["vuelva"],
            },
            {
                "before": "Es cierto que ellos",
                "after":  "a España en el año 2016.",
                "hint":   "ir",
                "answer": "fueron",
                "alts":   [],
            },
        ],
    },
    # ── Lesson 2: violet sheet ────────────────────────────────────────────────
    "2": {
        "title": "Voluntad y Deseo",
        "subtitle": "Subjuntivo con Expresiones de Voluntad",
        "intro": [
            {
                "type": "rule",
                "text": (
                    "Cuando una oración de dos cláusulas empieza con una de estas expresiones "
                    "y las dos cláusulas tienen sujetos diferentes, se usa el indicativo en la "
                    "primera cláusula y el subjuntivo en la segunda."
                ),
            },
            {
                "type": "examples",
                "items": [
                    "Yo quiero que tú me <em>visites</em> este verano a fines de julio.",
                    "Mamá insiste en que los niños <em>hagan</em> la tarea antes de ver la televisión.",
                    "Ojalá que Raúl <em>tenga</em> dinero suficiente para el viaje.",
                ],
            },
            {
                "type": "note",
                "marker": "★",
                "text": (
                    "Con el verbo <strong>decir</strong>, se requiere el subjuntivo en la segunda "
                    "cláusula sólo cuando <em>decir</em> implica un mandato."
                ),
                "examples": [
                    "La maestra dice que nadie <em>hable</em> durante el examen. → mandato",
                    "La maestra dice que el examen es el viernes. → información",
                ],
            },
            {
                "type": "note",
                "marker": "△",
                "text": (
                    "Con <strong>aconsejar, dejar, permitir</strong> y <strong>prohibir</strong>, "
                    "se puede usar un pronombre de complemento indirecto con un infinitivo en la "
                    "segunda cláusula en vez del subjuntivo."
                ),
                "examples": [
                    "Mis padres no me dejan <em>usar</em> el carro.",
                    "Mis padres no dejan que yo <em>use</em> el carro.",
                ],
            },
            {
                "type": "rule",
                "text": (
                    "Cuando no hay un cambio de sujeto en la segunda cláusula, se quita "
                    "\"que\" y se usa el infinitivo."
                ),
                "examples": [
                    "Queremos <em>salir</em> al mediodía.",
                ],
            },
        ],
        "exercises": [
            {
                "before": "El jefe exige que los empleados",
                "after":  "el proyecto esta semana.",
                "hint":   "terminar",
                "answer": "terminen",
                "alts":   [],
            },
            {
                "before": "Roberto",
                "after":  "que vayamos por otra calle para evitar el accidente.",
                "hint":   "sugerir",
                "answer": "sugiere",
                "alts":   [],
            },
            {
                "before": "Mis padres se oponen a que yo",
                "after":  ".",
                "hint":   "manejar",
                "answer": "maneje",
                "alts":   [],
            },
            {
                "before": "Luisa y yo",
                "after":  "que tú nos esperes aquí.",
                "hint":   "preferir",
                "answer": "preferimos",
                "alts":   [],
            },
            {
                "before": "Ojalá que San Nicolás",
                "after":  "muchos regalos.",
                "hint":   "traer",
                "answer": "traiga",
                "alts":   [],
            },
            {
                "before": "¡Cuidado, Pablito! Yo no",
                "after":  "que te caigas.",
                "hint":   "querer",
                "answer": "quiero",
                "alts":   [],
            },
            {
                "before": "El letrero dice que la película",
                "after":  "a las 8:30.",
                "hint":   "empezar",
                "answer": "empieza",
                "alts":   [],
            },
            {
                "before": "El médico me aconsejó",
                "after":  "el estrés.",
                "hint":   "reducir",
                "answer": "reducir",
                "alts":   [],
            },
        ],
    },
}

# ── Lessons registry ──────────────────────────────────────────────────────────

LESSONS = {
    "vocabulary": {
        "1": {
            "title":    "Vocabulario: Lección 5",
            "subtitle": "Un Festival de Arte",
            "words":    VOCABULARY,
        },
        "2": {
            "title":    "Vocabulario: Lección 4",
            "subtitle": "El Mundo del Trabajo",
            "words":    VOCABULARY_L4,
        },
        "3": {
            "title":    "Vocabulario: Lección 6",
            "subtitle": "La Actualidad",
            "words":    VOCABULARY_L6,
        },
        "4": {
            "title":    "Vocabulario: Números",
            "subtitle": "Un Sinnúmero de Números",
            "words":    VOCABULARY_NUMBERS,
        },
        "5": {
            "title":    "Expresiones Impersonales",
            "subtitle": "El Subjuntivo con Expresiones Impersonales",
            "words":    VOCABULARY_SUBJ_IMPERSONAL,
        },
        "6": {
            "title":    "Duda e Incertidumbre",
            "subtitle": "El Subjuntivo con Expresiones de Duda",
            "words":    VOCABULARY_SUBJ_DOUBT,
        },
        "7": {
            "title":    "Voluntad y Deseo",
            "subtitle": "Expresiones de Voluntad y Deseo con el Subjuntivo",
            "words":    VOCABULARY_SUBJ_WILL,
        },
    },
    "practica": PRACTICA_LESSONS,
}
